server:
    port: 8000

spring:

    datasource:
        # url: jdbc:h2:mem:testdb
        # username: sa
        # password:

        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/test

    # h2:
    #     console:
    #         enabled: true
    #     path: /h2-console
    #     settings:
    #         trace: false
    #         web-allow-others: true

    redis:
        host: 127.0.0.1
        # Redis 服务器连接端口
        port: 6379
        # Redis 数据库索引（默认为 0）
        database: 0
        # Redis 服务器连接密码（默认为空）
        password:
        jedis:
            pool:
                #连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接超时时间（毫秒）
                timeout: 5000

mybatis:
    mapperLocations: classpath:mapper/**/*.xml

logging:
    level:
        com.justdoit.springboottest.mapper.UserMapper: debug

kafka:
    bootstrapAddress: localhost:9092
    topic:
        test: test
        user: user
    consumer:
        groupId:
            test: test
            user: user

enable:
    security: false
    redis: false
    kafka: false
